<?php
if (!defined('ABSPATH')) exit;
class DN_GitHub_Updater {
    private $file,$cfg;
    public function __construct($file,$cfg){$this->file=$file;$this->cfg=$cfg;add_filter('pre_set_site_transient_update_plugins',array($this,'check'));add_filter('plugins_api',array($this,'info'),10,3);add_filter('upgrader_source_selection',array($this,'source'),10,4);}
    private function settings(){ $p=$this->cfg['option_prefix']; return array('owner'=>get_option($p.'owner',''),'repo'=>get_option($p.'repo',''),'token'=>get_option($p.'token','')); }
    private function release(){ $s=$this->settings(); if(!$s['owner']||!$s['repo']) return false; $url='https://api.github.com/repos/'.rawurlencode($s['owner']).'/'.rawurlencode($s['repo']).'/releases/latest'; $args=array('timeout'=>15,'headers'=>array('Accept'=>'application/vnd.github+json','User-Agent'=>'DealNest-Updater')); if($s['token']) $args['headers']['Authorization']='Bearer '.$s['token']; $r=wp_remote_get($url,$args); if(is_wp_error($r)||wp_remote_retrieve_response_code($r)!==200) return false; $d=json_decode(wp_remote_retrieve_body($r),true); return is_array($d)?$d:false; }
    public function check($t){ if(!is_object($t)) $t=new stdClass(); $r=$this->release(); if(!$r||empty($r['tag_name'])) return $t; $v=ltrim($r['tag_name'],'vV'); if(version_compare($v,$this->cfg['version'],'>')){ $asset=$this->asset($r); if($asset) $t->response[$this->plugin_basename()]=array('slug'=>$this->cfg['slug'],'plugin'=>$this->plugin_basename(),'new_version'=>$v,'url'=>!empty($r['html_url'])?$r['html_url']:'','package'=>$asset); } return $t; }
    private function asset($r){ if(empty($r['assets'])) return false; foreach($r['assets'] as $a){ if(isset($a['name'])&&$a['name']===$this->cfg['asset']) return $a['browser_download_url']??false; } return false; }
    private function plugin_basename(){ return plugin_basename($this->file); }
    public function info($false,$action,$args){ if($action!=='plugin_information'||empty($args->slug)||$args->slug!==$this->cfg['slug']) return $false; $r=$this->release(); if(!$r) return $false; return (object)array('name'=>$this->cfg['name'],'slug'=>$this->cfg['slug'],'version'=>ltrim($r['tag_name'],'vV'),'author'=>'DealNest','homepage'=>$r['html_url']??'','sections'=>array('description'=>'DealNest Affiliate Manager GitHub release.','changelog'=>isset($r['body'])?$r['body']:'')); }
    public function source($source,$remote_source,$upgrader,$hook_extra){ if(empty($hook_extra['plugin'])||$hook_extra['plugin']!==$this->plugin_basename()) return $source; $expected=untrailingslashit($remote_source).'/'.$this->cfg['slug']; if(is_dir($expected)) return $expected; return $source; }
}
